force-app/main/default/objects/Certification_Topic__c/Certification_Topic__c.object-meta.xml
<CustomObject>
    <description>The list of the topics that were passed at the time of the exam</description>
    <label>Certification Topic</label>
    <nameField>
        <label>Certification Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification_Topic__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <description>The users score for this topic</description>
    <label>Result</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Certification_Topic__c/fields/Weighting__c.field-meta.xml
<CustomField>
    <fullName>Weighting__c</fullName>
    <description>The value of the credential topic at the time of the certification</description>
    <label>Weighting</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <description>The details for each of the credentials provided by Salesforce</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Topic__c/Credential_Topic__c.object-meta.xml
<CustomObject>
    <description>The individual topics for each exam credential</description>
    <label>Credential Topic</label>
    <nameField>
        <label>Credential Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credential Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Topic__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <description>The credential this topic relates to</description>
    <label>Credential</label>
    <referenceTo>Credential__c</referenceTo>
    <relationshipLabel>Credential Topics</relationshipLabel>
    <relationshipName>Credential_Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Credential_Topic__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order of the topic</description>
    <label>Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credential_Topic__c/fields/Weighting__c.field-meta.xml
<CustomField>
    <fullName>Weighting__c</fullName>
    <description>The weighting applied to this topic</description>
    <label>Weighting</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/ExamEntryController.cls
public with sharing class ExamEntryController {
    public ExamEntryController() {

    }

    @AuraEnabled(cacheable=true)
    public static List<Credential__c> getCredentialList() {
        return [
            SELECT
                Id,
                Name
            FROM Credential__c
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Certification_Topic__c> getCertTopics(Id credentialId) {

        List<Credential_Topic__c> topicTemplates = [SELECT Credential__c, Name, Weighting__c, Order__c 
                                                    FROM Credential_Topic__c 
                                                    WHERE Credential__c = :credentialId
                                                    ORDER BY Order__c];
        List<Certification_Topic__c> topicList = new List<Certification_Topic__c>();

        Integer pos = 0;
        for(Credential_Topic__c topic :topicTemplates) {
            topicList.add(new Certification_Topic__c(Name = topic.Name, Weighting__c = topic.Weighting__c, Result__c = 0, Order__c = pos++));
        }

        return topicList;            
    }
}