force-app/main/default/objects/Certification_Topic__c/Certification_Topic__c.object-meta.xml
<CustomObject>
    <description>The list of the topics that were passed at the time of the exam</description>
    <label>Certification Topic</label>
    <nameField>
        <label>Certification Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification_Topic__c/fields/Weighting__c.field-meta.xml
<CustomField>
    <fullName>Weighting__c</fullName>
    <description>The value of the credential topic at the time of the certification</description>
    <label>Weighting</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Credential__c/Credential__c.object-meta.xml
<CustomObject>
    <description>The details for each of the credentials provided by Salesforce</description>
    <label>Credential</label>
    <nameField>
        <label>Credential Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential__c/fields/Number_of_Questions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Questions__c</fullName>
    <label>Number of Questions</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credential__c/fields/Passing_Score__c.field-meta.xml
<CustomField>
    <fullName>Passing_Score__c</fullName>
    <description>The score required to pass the exam</description>
    <label>Passing Score</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Credential_Topic__c/Credential_Topic__c.object-meta.xml
<CustomObject>
    <description>The individual topics for each exam credential</description>
    <label>Credential Topic</label>
    <nameField>
        <label>Credential Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credential Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_Topic__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <description>The credential this topic relates to</description>
    <label>Credential</label>
    <referenceTo>Credential__c</referenceTo>
    <relationshipLabel>Credential Topics</relationshipLabel>
    <relationshipName>Credential_Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Credential_Topic__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order of the topic</description>
    <label>Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credential_Topic__c/fields/Weighting__c.field-meta.xml
<CustomField>
    <fullName>Weighting__c</fullName>
    <description>The weighting applied to this topic</description>
    <label>Weighting</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/ExamEntryController_Test.cls
@isTest
public class ExamEntryController_Test {

    @isTest 
    private static void getCertTopics_Found() {

        // Arrange
        Credential__c cred = new Credential__c(Name = 'Test Credential 1',Passing_Score__c = 65, Number_of_Questions__c = 60);
        insert cred;

        List<Credential_Topic__c> topics = new List<Credential_Topic__c>{
            new Credential_Topic__c(Credential__c = cred.Id, Name = 'Topic 2', Weighting__c = 25, Order__c = 2),
            new Credential_Topic__c(Credential__c = cred.Id, Name = 'Topic 1', Weighting__c = 75, Order__c = 1)
        };
        insert topics;
        
        // Act
        Test.startTest();
        List<Certification_Topic__c> result = ExamEntryController.getCertTopics(cred.Id);
        Test.stopTest();
        
        // Assert
        Assert.areEqual(2, result.size(), 'Should have records');
        Assert.areEqual(0, result[0].Order__c, 'Should be order 1');
        Assert.areEqual(1, result[1].Order__c, 'Should be order 2');
    }
}